version: '2'
services:
    jhpng1-app:
        image: jhpng1
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:sqlserver://jhpng1-mssql:1433;database=jhpng1
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jhpng1-mssql:
        extends:
            file: mssql.yml
            service: jhpng1-mssql
